#! /bin/sh

bspc monitor -d 1 2 3 4

bspc config border_width			3
bspc config window_gap				3

bspc config split_ratio				0.5
bspc config single_monocle			false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config gapless_monocle			true

bspc config presel_feedback_color "#1a1a1a"
bspc config active_border_color		"#4fc3f7"
bspc config focused_border_color "#4fc3f7"
bspc config normal_border_color "#1a1a1a"

bspc rule -a \* rectangle=1280x720+0+0 center=true
bspc rule -a Galculator state=floating layer=normal rectangle=900x600+0+0
bspc rule -a Xarchiver state=floating layer=normal
bspc rule -a GParted state=floating layer=normal
bspc rule -a Pavucontrol:pavucontrol state=floating 
bspc rule -a Lxappearance state=floating layer=normal
bspc rule -a kitty state=floating layer=normal sticky=on 
#bspc rule -a mpv desktop='^2' state=floating layer=normal follow=on
#bspc rule -a Gimp desktop='^3' follow=on
#bspc rule -a obs desktop='^4' follow=on

# Start Up
xsetroot -cursor_name left_ptr &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
dunst -config ~/.config/bspwm/dunst/dunstrc &
picom --config ~/.config/bspwm/picom/picom.conf --animations -b &
nitrogen --restore &
xfce4-power-manager &

## Polybar
~/.config/bspwm/scripts/polybar-bspwm &

## apps for systray if enabled
# volumeicon &
nm-applet &
# (re)load sxhkd for keybinds
if hash sxhkd >/dev/null 2>&1; then
	pkill sxhkd
	sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" &
fi
